enum ECapability {
    /** 电源通断状态 */
    POWER = 'power',
    /** 表示无线信号强度 */
    RSSI = 'rssi',
    /** 固件升级 */
    OTA = 'ota',
    /** 当前检测 */
    DETECT = 'detect',
    /** 电池剩余电量 */
    BATTERY = 'battery',
    /** 开关能力 */
    TOGGLE = 'toggle',
    /** (窗帘)某种程度的百分比 */
    PERCENTAGE = 'percentage',
    /** (窗帘)电机开合状态 */
    MOTOR_CONTROL = 'motor-control',
    /** (窗帘)电机正反转设置 */
    MOTOR_REVERSE = 'motor-reverse',
    /** 窗帘校准行程 */
    MOTOR_CLB = 'motor-clb',
    /** 温度 */
    TEMPERATURE = 'temperature',
    /** 相对湿度 */
    HUMIDITY = 'humidity',
    /** 按键 */
    PRESS = 'press',
    /** 颜色 */
    COLOR_RGB = 'color-rgb',
    /** 色温 */
    COLOR_TEMPERATURE = 'color-temperature',
    /** 亮度 */
    BRIGHTNESS = 'brightness',
    /** 摄像头视频流能力 */
    CAMERA_STREAM = 'camera-stream',
    /** 通电反应 */
    STARTUP = 'startup'
}

export { ECapability }